version: "3.9"

services:

  up:
    image: unifiedplanning
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unifiedplanning
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=$DISPLAY
    volumes:
    - $PWD/test:/home/planner/test
    - $HOME/playground:/home/planner/playground


